class grafo(object):
            provinciaFG = {
                'Accadia': [{'Deliceto':9},{'Monteleone di Puglia':6},{'Panni':9}, {'Sant Agata':4}],
                  'Alberona': [{'Biccari':7},{'Lucera':20},{'Roseto Valfortore':7},{'Volturara Appula':9},{'Volturino':5}],
                  'Anzano di Puglia' : [{'Monteleone di Puglia':5} ,{'Sant Agata':9}],
                  'Apricena' : [{'Poggio Imperiale':8},{'Lesina':11},{'San Nicandro Garganico':11},{'San Severo':12},{'San Paolo di Civitate':16},{'Rignano Garganico':17},{'San Marco in Lamis':18}],
                  'Ascoli Satriano': [{'Candela':8},{'Castelluccio dei Sauri':13},{'Ordona':13}, {'Deliceto':15},{'Stornarella':15},{'Orta Nova':18}, {'Foggia':28},{'Cerignola':29}],
                  'Biccari': [{'Castelluccio Valmaggiore':6},{'Alberona':7},{'Celle di San Vito':8},{'Faeto':8},{'Roseto Valfortore':8}, {'Troia':10},{'Lucera':17}],
                  'Bovino': [{'Deliceto':5},{'Panni':6},{'Orsara di Puglia':7},{'Accadia':10,},{'Castelluccio dei Sauri':13}],
                  'Cagnano Varano': [{'Carpino':7},{'Ischitella':13},{'San Marco in Lamis':17},{'San Nicandro Garganico':17},{'Monte Sant Angelo':21}],
                   'Candela' : [{'Rocchetta Sant Antonio':6},{'Ascoli Satriano':8},{'Sant Agata':11},{'Deliceto':14}],
                    'Carapelle': [{'Orta Nova':4},{'Ordona':8},{'Foggia':16},{'Manfredonia':34}],
                    'Carlantino': [{'Celenza Valfortore':4},{'Casalnuovo Monterotaro':11}],
                    'Carpino': [{'Cagnano Varano':7},{'Ischitella':8},{'Vico del Gargano':10},{'Monte Sant Angelo':18}],
                    'Casalnuovo Monterotaro':[{'Castelnuovo della Daunia':4},{'Pietramontecorvino':9},{'Carlantino':11},
                                              {'Celenza Valfortore':12}],
                    'Castelluccio dei Sauri': [{'Deliceto':12},{'Ascoli Satriano':13},{'Bovino':13},{'Troia':15},{'Foggia':18},{'Orsara di Puglia':18}],
                    'Castelluccio Valmaggiore': [{'Celle di San Vito':2},{'Biccari':6},{'Troia':10}],
                    'Castelnuovo della Daunia': [{'Casalnuovo Monterotaro':4},{'Pietramontecorvino':5},{'Torremaggiore':19},{'Lucera':20}],
                    'Celenza Valfortore': [{'Carlantino':4},{'San Marco la Catola':5},{'Volturara Appula':10},{'Casalnuovo Monterotaro':12},{'Pietramontecorvino':13},
                                           {'Motta Montecorvino':13}],
                    'Celle di San Vito': [{'Faeto':2},{'Castelluccio Valmaggiore':2},{'Biccari':8},{'Orsara di Puglia':8},{'Troia':12}],
                    'Cerignola' : [],
                    #'Cerignola': [{'Stornara':11},{'Stornarella':14},{'Orta Nova':17},{'Carapelle':21},{'Zapponeta':22},{'Ascoli Satriano':29},{'Manfredonia':40}],
                    'Chieuti': [{'Serracapriola':4}],
                    'Deliceto': [{'Bovino':5},{'Sant Agata':8},{'Accadia':8},{'Castelluccio dei Sauri':12},{'Candela':14},{'Ascoli Satriano':15}],
                    'Faeto': [{'Celle di San Vito':2},{'Roseto Valfortore':7},{'Biccari':8},{'Orsara di Puglia':10}],
                    'Foggia':[],
                    'Ischitella': [{'Rodi Garganico':3},{'Vico del Gargano':5},{'Carpino':7},{'Cagnano Varano':13}],
                    'Isole Tremiti': [{}],
                    'Lesina':[{'Poggio Imperiale':4},{'Apricena':11},{'San Paolo di Civitate':15},{'Serracapriola':17},{'San Nicandro Garganico':18}],
                    'Lucera': [{'Troia':16},{'Biccari':17},{'Pietramontecorvino':18},{'Volturino':18},{'Foggia':19},{'Alberona':20},
                               {'Castelnuovo della Daunia':20},{'San Severo':20},{'Torremaggiore':21}],
                    'Manfredonia' :[],
                    'Mattinata': [{'Monte Sant Angelo':7},{'Vieste':22}],
                    'Monteleone di Puglia':[{'Anzano di Puglia':5},{'Accadia':6},{'Panni':6},{'Sant Agata':10}],
                    'Monte Sant Angelo' :[{'Mattinata':7},{'Manfredonia':10},{'Carpino':18},{'San Giovanni Rotondo':20},{'Cagnano Varano':21},{'Vico del Gargano':22},{'Vieste':26},{'San Marco in Lamis':27}],
                    'Motta Montecorvino': [{'Volturino':3},{'Pietramontecorvino':4},{'Volturara Appula':5},{'Celenza Valfortore':13}],
                    'Orsara di Puglia': [{'Panni':7},{'Bovino':7},{'Celle di San Vito':8},{'Troia':10},{'Faeto':10},{'Castelluccio dei Sauri':18}],
                    'Orta Nova': [{'Carapelle':4},{'Stornara':7},{'Ordona':7},{'Stornarella':8},{'Cerignola':17},{'Ascoli Satriano':18}],
                    'Panni': [{'Bovino':6},{'Monteleone di Puglia':6},{'Orsara di Puglia':7},{'Accadia':8}],
                    'Peschici': [{'Vico del Gargano':7},{'Vieste':15}],
                    'Pietramontecorvino': [{'Motta Montecorvino':4},{'Castelnuovo della Daunia':5},{'Volturino':7},{'Casalnuovo Monterotaro':9},{'Celenza Valfortore':13},{'Lucera':18}],
                    'Poggio Imperiale': [{'Lesina':4},{'Apricena':8},{'San Paolo di Civitate':13},{'San Nicandro Garganico':17}],
                    'Rignano Garganico': [{'San Marco in Lamis':6},{'Apricena':17},{'San Severo':18},{'Foggia':24}],
                    'Rocchetta Sant Antonio' : [{'Candela':6},{'Sant Agata': 9}],
                    'Rodi Garganico' : [{'Ischitella':3},{'Vico del Gargano':7}],
                    'Roseto Valfortore': [{'Alberona':7},{'Faeto':8},{'Biccari':9}],
                    'San Giovanni Rotondo':[],
                    'San Marco in Lamis': [{'Rignano Garganico':6},{'San Giovanni Rotondo':6},{'San Nicandro Garganico':15},{'Cagnano Varano':17},
                                           {'Apricena':	18},{'San Severo':22},{'Manfredonia':24},{'Monte Sant Angelo':27},{'Foggia':29}],
                    'San Marco la Catola': [{'Celenza Valfortore':5},{'Volturara Appula':5}],
                    'San Nicandro Garganico': [{'Apricena':12},{'San Marco in Lamis': 15},{'Poggio Imperiale':17},{'Cagnano Varano':17},
                                               {'Lesina':18}],
                    'San Paolo di Civitate': [{'Torremaggiore':6},{'San Severo':11},{'Serracapriola':12},{'Poggio Imperiale':13},{'Lesina':15},
                                              {'Apricena':16}],
                    'San Severo':[],
                    'Sant Agata' :[{'Accadia':4},{'Deliceto':8},{'Anzano di Puglia':9},{'Rocchetta Sant Antonio':9},{'Monteleone di Puglia':10},{'Candela':11}],
                    'Serracapriola': [{'Chieuti':4},{'San Paolo di Civitate':12},{'Lesina':17},{'Torremaggiore':18}],
                    'Stornara': [{'Stornarella':5},{'Orta Nova':7},{'Cerignola':11}],
                    'Stornarella': [{'Stornara':5},{'Orta Nova':8},{'Ascoli Satriano':15}],
                    'Torremaggiore': [{'San Paolo di Civitate':6},{'San Severo':6},{'Serracapriola':17},{'Castelnuovo della Daunia':19},
                                      {'Lucera':21}],
                    'Troia': [{'Castelluccio Valmaggiore':10},{'Orsara di Puglia':10},{'Biccari':11},{'Celle di San Vito':12},
                              {'Castelluccio dei Sauri':15},{'Lucera':16},{'Foggia':22}],
                    'Vico del Gargano': [{'Ischitella':5},{'Peschici':7},{'Rodi Garganico':7},{'Carpino':10},{'Vieste':18},{'Monte Sant Angelo':21}],
                    'Vieste': [{'Peschici':15},{'Vico del Gargano':18},{'Mattinata':22},{'Monte Sant Angelo':26}],
                    'Volturara Appula': [{'San Marco la Catola':5},{'Motta Montecorvino':5},{'Volturino':6},{'Alberona':9},{'Celenza Valfortore':10}],
                    'Volturino': [{'Motta Montecorvino':4},{'Alberona':5},{'Volturara Appula':6},{'Pietramontecorvino':7},{'Lucera':18}],
                    'Ordona': [{'Orta Nova':7},{'Carapelle':8},{'Ascoli Satriano':13},{'Foggia':18}],
                    'Zapponeta': [{'Manfredonia':19},{'Cerignola':22}],


                                }

            provinciaBT = {
                'Andria' :	[],
                'Barletta' : [],
                'Bisceglie' : [],
                'Canosa di Puglia' : [{'San Ferdinando di Puglia':9},{'Minervino Murge':15},{'Andria':19},{'Barletta':21}],
                'Margherita di Savoia' : [{'Trinitapoli':6},{'Barletta':14}],
                'Minervino Murge' :	[{'Spinazzola':13},{'Canosa di Puglia':15},{'Andria':24}],
                'San Ferdinando di Puglia' : [{'Trinitapoli':6},{'Canosa di Puglia':9},{'Barletta':18}],
                'Spinazzola' :[{'Minervino Murge':13},{'Andria':34}],
                'Trani'	:[],
                'Trinitapoli' : [{'Margherita di Savoia':6},{'San Ferdinando di Puglia':6},{'Barletta':18}]
            }

            provinciaLE ={
                'Alessano' : [{'Corsano':3},{'Tiggiano':3},{'Salve':4},{'Morciano di Leuca':5},{'Tricase':5},{'Gagliano del Capo':6},{'Presicce-Acquarica':6},{'Specchia':6},{'Castrignano del Capo':6}],
                'Alezio': [{'Sannicola':3},{'Tuglie':4},{'Gallipoli':5},{'Parabita':6},{'Matino':7}],
                'Alliste' :[{'Racale':2},{'Ugento':6}],
                'Andrano':[{'Diso':3},{'Spongano':4},{'Montesano Salentino':5},{'Surano':6},{'Tricase':6}],
                'Aradeo': [{'Seclì':2},{'Neviano':3},{'Galatina':6},{'Cutrofiano':6}],
                'Arnesano' :[{'Monteroni di Lecce':1},{'Carmiano':4},{'Novoli':6},{'Lecce':7},{'Copertino':8},{'Leverano':9}],
                'Bagnolo del Salento': [{'Cannole':2},{'Palmariggi':3},{'Cursi':3},{'Castrignano de Greci':5},{'Maglie':6}],
                'Botrugno': [{'San Cassiano':1},{'Sanarica':3},{'Scorrano':4},{'Supersano':9}],
                'Calimera': [{'Martignano':2},{'Caprarica di Lecce':3},{'Castri di Lecce':3},{'Vernole':5},{'Zollino':6},{'Martano':6},{'Melendugno':6},{'Carpignano Salentino':8}],
                'Campi Salentina': [{'Novoli':3},{'Squinzano':4},{'Trepuzzi':5},{'Salice Salentino':5},{'Guagnano':6},{'Veglie':8}],
                'Cannole' : [{'Bagnolo del Salento':2},{'Palmariggi':4},{'Carpignano Salentino':4},{'Castrignano de Greci':6},{'Otranto':9}],
                'Caprarica di Lecce': [{'Castri di Lecce':2},{'Martignano':3},{'Calimera':3},{'Sternatia':4},{'Lizzanello':5},{'San Donato di Lecce':6},
                                       {'Cavallino':7}],
                'Carmiano': [{'Novoli':4},{'Arnesano':4},{'Veglie':7},{'Leverano':7},{'Copertino':8}],
                'Carpignano Salentino' :[{'Martano':3},{'Cannole':4},{'Castrignano de Greci':5},{'Calimera':8},{'Melendugno':9},{'Otranto':12}],
                'Casarano' :[],#ospedale
                'Castri di Lecce': [{'Caprarica di Lecce':2},{'Calimera':3},{'Vernole':4},{'Lizzanello':5}],
                'Castrignano de Greci':[{'Melpignano':2},{'Cursi':3},{'Martano':3},{'Corigliano d Otranto':4},{'Carpignano Salentino':4},{'Bagnolo del Salento':5},{'Cannole':6}],
                'Castrignano del Capo': [{'Patù':1},{'Gagliano del Capo':2},{'Morciano di Leuca':4},{'Alessano':7}],
                'Cavallino':[{'Lizzanello':2},{'San Cesario di Lecce':3},{'San Donato di Lecce':5},{'Lecce':6},{'Caprarica di Lecce':7}],
                'Collepasso' : [{'Parabita':4},{'Matino':5},{'Neviano':6},{'Casarano':6},{'Cutrofiano':7},{'Supersano':9}],
                'Copertino' : [],#ospedale
                'Corigliano d Otranto':[{'Melpignano':3},{'Castrignano de Greci':4},{'Zollino':5},{'Soleto':5},{'Sogliano Cavour':6},{'Maglie':6},
                                        {'Martano':6},{'Cutrofiano':6},{'Galatina':8}],
                'Corsano':[{'Tiggiano':2},{'Alessano':3}],
                'Cursi':[{'Melpignano':2},{'Castrignano de Greci':3},{'Bagnolo del Salento':3},{'Maglie':4}],
                'Cutrofiano':[{'Sogliano Cavour':3},{'Galatina':6},{'Aradeo':6},{'Corigliano d Otranto':6},{'Collepasso':7},{'Neviano':8},{'Maglie':8},{'Melpignano':9},{'Scorrano':9},{'Supersano':13}],
                'Diso':[{'Spongano':2},{'Ortelle':3},{'Andrano':3}],
                'Gagliano del Capo':[{'Castrignano del Capo':2},{'Alessano':6}],
                'Galatina':[],#ospedale
                'Galatone':[{'Seclì':4},{'Nardò':5},{'Neviano':5},{'Sannicola':6},{'Galatina':9},{'Gallipoli':12}],
                'Gallipoli':[],#ospedale
                'Giuggianello':[{'Sanarica':2},{'Muro Leccese':3},{'Palmariggi':4},{'Minervino di Lecce':5},{'Poggiardo':5},{'Giurdignano':6}],
                'Giurdignano': [{'Uggiano la Chiesa':3},{'Minervino di Lecce':4},{'Otranto':4},{'Palmariggi':5},{'Giuggianello':6}],
                'Guagnano':[{'Salice Salentino':2},{'Campi Salentina':6}],
                'Lecce':[],#ospedale
                'Lequile':[{'San Pietro in Lama':1},{'San Cesario di Lecce':2},{'Monteroni di Lecce':4},{'San Donato di Lecce':6 },{'Lecce':6},{'Copertino':8},{'Soleto':14},{'Galatina':15}],
                'Leverano':[{'Copertino':5},{'Veglie':6},{'Carmiano':7},{'Arnesano':10},{'Nardò':13}],
                'Lizzanello':[{'Cavallino':2},{'Castri di Lecce':5},{'Caprarica di Lecce':6},{'Vernole':7},{'Lecce':7}],
                'Maglie':[{'Scorrano':3},{'Cursi':4},{'Muro Leccese':4},{'Melpignano':5},{'Corigliano d Otranto':6},{'Bagnolo del Salento':6},
                          {'Palmariggi':7},{'Cutrofiano':8}],
                'Martano':[{'Cavallino':2},{'Castri di Lecce':5},{'Caprarica di Lecce':6},{'Vernole':7},{'Lecce':7}],
                'Martignano':[{'Caprarica di Lecce':2},{'Calimera':2},{'Sternatia':3},{'Zollino':4}],
                'Matino':[{'Parabita':2},{'Casarano':3},{'Collepasso':5},{'Melissano':6},{'Taviano':7},{'Alezio':7},{'Gallipoli':12}],
                'Melendugno':[{'Vernole':3},{'Calimera':6},{'Carpignano Salentino':9},{'Otranto':18}],
                'Melissano':[{'Racale':3},{'Taviano':3},{'Casarano':6},{'Ugento':6},{'Matino':7}],
                'Melpignano':[{'Castrignano de Greci':2},{'Cursi':2},{'Corigliano d Otranto':3},{'Maglie':4},{'Cutrofiano':9}],
                'Miggiano':[{'Montesano Salentino':2},{'Specchia':3},{'Tricase':5},{'Ruffano':6}],
                'Minervino di Lecce':[{'Uggiano la Chiesa':3},{'Giurdignan':4},{'Giuggianello':4},{'Poggiardo':5},{'Santa Cesarea Terme':7}],
                'Monteroni di Lecce':[{'Arnesano':1},{'San Pietro in Lama':3},{'Lequile':4},{'Copertino':7},{'Lecce':7}],
                'Montesano Salentino':[{'Miggiano':2},{'Andrano':5},{'Tricase':6},{'Surano':6},{'Ruffano':6},{'Nociglia':7},{'Supersano':8}],
                'Morciano di Leuca':[{'Salve':2},{'Patù':2},{'Castrignano del Capo':4},{'Alessano':5}],
                'Muro Leccese':[{'Sanarica':2},{'Giuggianello':3},{'Scorrano':4},{'Maglie':4},{'Palmariggi':5}],
                'Nardò':[{'Galatone':5},{'Copertino':11},{'Galatina':12},{'Leverano':13},{'Porto Cesareo':15},{'Veglie':19},{'Salice Salentino':24}],
                'Neviano':[{'Seclì':1},{'Aradeo':3},{'Tuglie':4},{'Sannicola':4},{'Galatone':5},{'Collepasso':6},{'Parabita':6},{'Cutrofiano':8}],
                'Nociglia':[{'Surano':2},{'Poggiardo':5},{'Montesano Salentino':7},{'Supersano':8}],
                'Novoli':[{'Campi Salentina':3},{'Carmiano':4},{'Trepuzzi':4},{'Arnesano':6},{'Veglie':9},{'Lecce':11}],
                'Ortelle':[{'Poggiardo':2},{'Diso':7},{'Spongano':3},{'Santa Cesarea Terme':6}],
                'Otranto':[{'Giurdignano':4},{'Uggiano la Chiesa':5},{'Palmariggi':8},{'Cannole':9},{'Santa Cesarea Terme':13},{'Carpignano Salentino':13},{'Melendugno':18}],
                'Palmariggi':[{'Bagnolo del Salento':3},{'Cannole':4},{'Giuggianello':4},{'Giurdignano':5},{'Muro Leccese':5},{'Maglie':7},{'Otranto':8}],
                'Parabita':[{'Matino':2},{'Tuglie':4},{'Collepasso':4},{'Alezio':6},{'Neviano':6}],
                'Patù':[{'Castrignano del Capo':1},{'Morciano di Leuca':2}],
                'Poggiardo':[{'Ortelle':2},{'Spongano':4},{'Giuggianello':4},{'Sanarica':5},{'Nociglia':5},{'Minervino di Lecce':5},{'Santa Cesarea Terme':7}],
                'Racale':[{'Alliste':2},{'Taviano':2},{'Melissano':3},{'Ugento':7}],
                'Ruffano':[{'Supersano':4},{'Taurisano':4},{'Miggiano':6},{'Montesano Salentino':6},{'Specchia':7},{'Casarano':8},{'Presicce-Acquarica':9},{'Ugento':10}],
                'Salice Salentino':[{'Guagnano':2},{'Campi Salentina':5},{'Veglie':6},{'Nardò':24}],
                'Salve':[{'Morciano di Leuca':2},{'Alessano':4},{'Presicce-Acquarica':5},{'Ugento':14}],
                'Sanarica':[{'Muro Leccese':2},{'Giuggianello':2},{'Botrugno':3},{'Scorrano':4},{'Poggiardo':5}],
                'San Cesario di Lecce':[{'Lequile':2},{'Cavallino':4},{'San Donato di Lecce':5},{'Lecce':6}],
                'San Donato di Lecce':[{'San Cesario di Lecce':4},{'Cavallino':5},{'Caprarica di Lecce':6},{'Lequileì':6},{'Sternatia':6},{'Soleto':9}],
                'Sannicola':[{'Tuglie':3},{'Alezio':4},{'Neviano':4},{'Galatone':6},{'Gallipoli':7}],
                'San Pietro in Lama':[{'Lequile':1},{'Monteroni di Lecce':3},{'Copertino':7}],
                'Santa Cesarea Terme':[{'Ortelle':6},{'Minervino di Lecce':7},{'Poggiardo':7},{'Uggiano la Chiesa':7},{'Otranto':13}],
                'Scorrano':[],#ospedale
                'Seclì':[{'Neviano':1},{'Aradeo':2},{'Galatone':4},{'Galatina':8}],
                'Sogliano Cavour':[{'Cutrofiano':3},{'Galatina':4},{'Corigliano d Otranto':6}],
                'Soleto':[{'Galatina':4},{'Sternatia':4},{'Zollino':4},{'Corigliano d Otranto':5},{'San Donato di Lecce':9},{'Lequile':14}],
                'Specchia':[{'Miggiano':3},{'Tricase':5},{'Presicce-Acquarica':5},{'Alessano':6},{'Ruffano':7}],
                'Spongano':[{'Surano':2},{'Diso':2},{'Ortelle':3},{'Andrano':4},{'Poggiardo':4}],
                'Squinzano':[{'Trepuzzi':4},{'Campi Salentina':5},{'Lecce':14}],
                'Sternatia':[{'Zollino':3},{'Martignano':3},{'Soleto':4},{'Caprarica di Lecce':5},{'San Donato di Lecce':6}],
                'Supersano': [{'Ruffano':4},{'Casarano':7},{'Nociglia':7},{'Montesano Salentino':8},{'Botrugno':9},{'San Cassiano':9},{'Collepasso':9},
                              {'Scorrano':10},{'Cutrofiano':13}],
                'Surano':[{'Nociglia':2},{'Spongano':2},{'Poggiardo':4},{'Andrano':6},{'Montesano Salentino':6}],
                'Surbo':[{'Lecce':5}],
                'Taurisano':[{'Ruffano':4},{'Ugento':6},{'Presicce-Acquarica':8}],
                'Taviano':[{'Racale':2},{'Melissano':3},{'Matino':7},{'Gallipoli':11}],
                'Tiggiano':[{'Corsano':2},{'Tricase':3},{'Alessano':4}],
                'Trepuzzi':[{'Novoli':4},{'Squinzano':4},{'Campi Salentina':5},{'Lecce':10}],
                'Tricase':[],#ospedale
                'Tuglie':[{'Sannicola':3},{'Parabita':4},{'Alezio':4},{'Neviano':4}],
                'Ugento':[{'Taurisano':6},{'Melissano':6},{'Alliste':6},{'Racale':7},{'Presicce-Acquarica':9},{'Ruffano':10},{'Casaran':10},{'Salve':14}],
                'Uggiano la Chiesa':[{'Giurdignano':7},{'Minervino di Lecce':3},{'Otranto':5},{'Santa Cesarea Terme':7}],
                'Veglie':[{'Salice Salentino':6},{'Leverano':6},{'Carmiano':7},{'Campi Salentina':8},{'Novoli':9},{'Nardò':19}],
                'Vernole':[{'Melendugno':3},{'Castri di Lecce':4},{'Calimera':5},{'Lizzanello':7},{'Lecce':13}],
                'Zollino':[{'Sternatia':3},{'Martignano':3},{'Soleto':4},{'Martano':5},{'Corigliano d Otranto':5},{'Calimera':6}],
                'San Cassiano':[{'Botrugno':1},{'Nociglia':2},{'Sanarica':4},{'Poggiardo':4},{'Supersano':9}],
                'Castro':[{'Diso':3},{'Santa Cesarea Terme':4},{'Ortelle':4}],
                'Porto Cesareo':[{'Nardò':15}],
                'Presicce-Acquarica':[{'Salve':	5},{'Specchia':5},{'Alessano':6},{'Taurisano':8},{'Ugento':9},{'Ruffano':10}]
            }
            provinciaBA = {
                "Bari": [],
                "Altamura": [],
                "Monopoli": [],
                "Putignano": [],
                "Acquaviva delle fonti": [],
                "Modugno": [{"Bari": 7}, {"Bitetto": 7}, {"Bitritto": 7}, {"Bitonto": 8}],
                "Bitritto": [{"Bari": 8}, {"Sannicandro di Bari": 5}, {"Adelfia": 6}, {"Bitetto": 7}, {"Modugno": 7}],
                "Triggiano": [],
                "Valenzano": [{"Bari": 9}, {"Capurso": 3}, {"Adelfia": 5}, {"Casamassima": 10}],
                "Capurso": [{"Bari": 10}, {"Triggiano": 2}, {"Valenzano": 3}, {"Cellamare": 3}, {"Noicottaro": 6},
                            {"Casamassima": 10}],
                "Adelfia": [{"Bari": 13}, {"Valenzano": 5}, {"Bitritto": 6}, {"Sannicandro di Bari": 6},
                            {"Casamassima": 7}, {"Acquaviva delle fonti": 12}],
                "Bitonto": [{"Bari": 14}, {"Palo del Colle": 6}, {"Modugno": 8}, {"Giovinazzo": 9}, {"Bitetto": 9},
                            {"Binetto": 10}, {"Terlizzi": 12}, {"Ruvo di Puglia": 17}, {"Toritto": 20},
                            {"Altamura": 33}],
                "Noicottaro": [{"Bari": 15}, {"Rutigliano": 3}, {"Cellamare": 6}, {"Capurso": 6}, {"Triggiano": 7},
                               {"Mola di Bari": 9}, {"Casamassima": 10}],
                "Giovinazzo": [{"Bari": 17}, {"Molfetta": 6}, {"Bitonto": 9}, {"Terlizzi": 12}],
                "Mola di Bari": [{"Bari": 21}, {"Noicottaro": 9}, {"Rutigliano": 9}, {"Conversano": 11},
                                 {"Polignano a Mare": 13}],
                "Alberobello": [{"Locorotondo": 8}, {"Noci": 9}, {"Castellana Grotte": 13}, {"Monopoli": 19}],
                "Binetto": [{"Grumo di puglia": 1}, {"Bitetto": 4}, {"Palo del Colle": 4}, {"Sannicandro di Bari": 8},
                            {"Bitonto": 10}, {"Toritto": 13}],
                "Casamassima": [{"Adelfia": 7}, {"Cellamare": 7}, {"Sammichele di Bari": 8},
                                {"Acquaviva delle fonti": 9}, {"Rutigliano": 9}, {"Turi": 10}, {"Capurso": 10},
                                {"Valenzano": 10}, {"Noicottaro": 10}],
                "Cassano delle Murge": [{"Acquaviva delle fonti": 6}, {"Santeramo in colle": 11},
                                        {"Sannicandro di Bari": 12}, {"Grumo di puglia": 14}, {"Altamura": 19}],
                "Castellana Grotte": [{"Putignano": 5}, {"Conversano": 10}, {"Noci": 11}, {"Alberobello": 13},
                                      {"Polignano a Mare": 13}, {"Monopoli": 13}],
                "Cellamare": [{"Capurso": 3}, {"Noicottaro": 5}, {"Casamassima": 7}],
                "Conversano": [{"Polignano a Mare": 9}, {"Turi": 10}, {"Castellana Grotte": 10}, {"Rutigliano": 10},
                               {"Mola di Bari": 11}, {"Putignano": 13}],
                "Corato": [{"Ruvo di puglia": 7}],
                "Gioia del colle": [{"Sammichele di Bari": 10}, {"Acquaviva delle fonti": 13},
                                    {"Santeramo in colle": 14}, {"Turi": 16}, {"Noci": 18}, {"Putignano": 17}],
                "Gravina di puglia": [{"Altamura": 11}, {"Poggiorsini": 18}, {"Ruvo di puglia": 33}],
                "Grumo di puglia": [{"Binetto": 1}, {"Sannicandro di Bari": 8}, {"Toritto": 12},
                                    {"Cassano delle Murge": 14}, {"Altamura": 24}],
                "Locorotondo": [{"Alberobello": 8}],
                "Modugno": [{"Bari": 7}, {"Bitetto": 7}, {"Bitritto": 7}, {"Bitonto": 8}],
                "Molfetta": [{"Giovinazzo": 6}, {"Terlizzi": 8}],
                "Noci": [{"Putignano": 7}, {"Alberobello": 9}, {"Castellana Grotte": 11}, {"Gioia del colle": 18}],
                "Noicottaro": [{"Rutigliano": 3}, {"Cellamare": 5}, {"Capurso": 6}, {"Triggiano": 7},
                               {"Mola di Bari": 9}, {"Casamassima": 10}, {"Bari": 15}],
                "Palo del Colle": [{"Binetto": 4}, {"Bitetto": 4}, {"Bitonto": 6}, {"Toritto": 15}],
                "Poggiorsini": [{"Altamura": 11}, {"Poggiorsini": 18}, {"Ruvo di puglia": 33}],
                "Polignano a Mare": [{"Monopoli": 8}, {"Conversano": 9}, {"Castellana Grotte": 13},
                                     {"Mola di Bari": 13}],
                "Rutigliano": [{"Noicottaro": 3}, {"Mola di Bari": 9}, {"Casamassima": 9}, {"Conversano": 10},
                               {"Turi": 11}],
                "Ruvo di puglia": [{"Terlizzi": 5}, {"Corato": 7}, {"Bitonto": 17}, {"Altamura": 32},
                                   {"Gravina in puglia": 33}],
                "Sammichele di Bari": [{"Turi": 7}, {"Casamassima": 8}, {"Acquaviva delle fonti": 9},
                                        {"Gioia del colle": 10}],
                "Sannicandro di Bari": [{"Bitritto": 5}, {"Bitetto": 6}, {"Adelfia": 6}, {"Grumo di puglia": 7},
                                       {"Binetto": 8}, {"Acquaviva delle fonti": 12}, {"Cassano delle Murge": 12}],
                "Santeramo in colle": [{"Cassano delle Murge": 11}, {"Acquaviva delle fonti": 14}, {"Gioia del colle": 14},
                                       {"Altamura": 17}],
                "Terlizzi": [{"Ruvo di puglia": 5}, {"Molfetta": 9}, {"Giovinazzo": 12}, {"Bitonto": 12}],
                "Toritto": [{"Grumo di puglia": 12}, {"Binetto": 13}, {"Palo del Colle": 15}, {"Altamura": 15},
                            {"Bitonto": 19}],
                "Turi": [{"Sammichele di Bari": 7}, {"Casamassima": 10}, {"Conversano": 10}, {"Rutigliano": 10},
                         {"Putignano": 11}, {"Gioia del colle": 16}],
                "Bitetto":[{"Binetto":4},{"Palo del Colle":4},{"Sannicandro di Bari":6},{"Bitritto":7},{"Modugno":7},{"Bitonto":9}]

            }
            provinciaTA = {'Avetrana': [{'Manduria': 10}],
                      'Carosino': [{'San Giorgio Ionico': 2}, {'Monteparano': 3}, {'Grottaglie': 9}],
                      'Castellaneta': [],
                      'Crispiano': [{'Statte': 5}, {'Montemesola': 10}, {'Martina Franca': 14}, {'Grottaglie': 18}],
                      'Faggiano': [{'Roccaforzata': 2}, {'San Giorgio Ionico': 4}, {'Pulsano': 5}],
                      'Fragagnano': [{'Sava': 8}, {'San Marzano di San Giuseppe': 4}, {'Grottaglie': 12},
                                     {'Lizzano': 5}],
                      'Ginosa': [{'Laterza': 7}, {'Castellaneta': 16}],
                      'Grottaglie': [],
                      'Laterza': [{'Ginosa': 7}, {'Castellaneta': 12}],
                      'Leporano': [{'Pulsano': 2}, {'Taranto': 9}],
                      'Lizzano': [{'Fragagnano': 5}, {'Sava': 9}, {'Torricella': 6}, {'Taranto': 9}],
                      'Manduria': [],
                      'Martina Franca': [],
                      'Maruggio': [{'Torricella': 7}, {'Sava': 9}, {'Manduria': 10}],
                      'Massafra': [{'Palagiano': 7}, {'Statte': 7}, {'Mottola': 8}, {'Crispiano': 10}],
                      'Monteiasi': [{'Carosino': 4}, {'San Giorgio Ionico': 5}, {'Grottaglie': 6}, {'Taranto': 15}],
                      'Montemesola': [{'Grottaglie': 9}, {'Crispiano': 10}, {'Statte': 11}, {'Taranto': 19}],
                      'Monteparano': [{'Roccaforzata': 2}, {'Carosino': 3}, {'San Giorgio Ionico': 3}, {'Taranto': 15}],
                      'Mottola': [{'Palagianello': 6}, {'Palagiano': 6}, {'Massafra': 8}, {'Castellaneta': 8},
                                  {'Martina Franca': 26}],
                      'Palagianello': [{'Castellaneta': 4}, {'Mottola': 6}, {'Palagiano': 8}],
                      'Palagiano': [{'Palagianello': 6}, {'Mottola': 6}, {'Massafra': 7}, {'Castellaneta': 10}],
                      'Pulsano': [{'Leporano': 2}, {'Faggiano': 5}, {'Taranto': 11}],
                      'Roccaforzata': [{'Taranto': 13}, {'Monteparano': 2}, {'San Giorgio Ionico': 2}, {'Faggiano': 2}],
                      'San Giorgio Ionico': [{'Taranto': 12}, {'Carosino': 2}, {'Roccaforzata': 2}, {'Monteiasi': 5},
                                             {'Monteparano': 3}, {'Faggiano': 4}],
                      'San Marzano di San Giuseppe': [{'Fragagnano': 4}, {'Sava': 7}, {'Grottaglie': 11}],
                      'Sava': [{'Manduria': 6}, {'Torricella': 7}, {'San Marzano di San Giuseppe': 7},
                               {'Fragagnano': 8}, {'Maruggio': 9}, {'Lizzano': 9}],
                      'Statte': [{'Crispiano': 4}, {'Massafra': 8}, {'Montemesola': 11}, {'Taranto': 17}],
                      'Taranto': [],
                      'Toricella': [{'Lizzano': 6}, {'Sava': 7}, {'Maruggio': 7}]

                      }
            provinciaBR = {'Ostuni': [],
                      'Brindisi': [],
                      'Carovigno': [{'Ostuni': 7}, {'San Vito dei Normanni': 7}, {'Brindisi': 25}],
                      'Ceglie Messapica': [{'Villa Castelli': 7}, {'San Michele Salentino': 10}, {'Ostuni': 10},
                                           {'Francavilla Fontana': 14}],
                      'Cellino San Marco': [{'San Pietro Vernotico': 3}, {'San Donaci': 4}, {'Brindisi': 17}],
                      'Cisternino': [{'Fasano': 11}, {'Ostuni': 13}],
                      'Erchie': [{'Torre Santa Susanna': 3}, {'San Pancrazio Salentino': 4}, {'Oria': 10}],
                      'Fasano': [{'Cisternino': 11}, {'Ostuni': 22}],
                      'Francavilla Fontana': [],
                      'Latiano': [{'Mesagne': 7}, {'Oria': 11}, {'San Michele Salentino': 11},
                                  {'San Vito dei Normanni': 11}, {'Francavilla Fontana': 20}],
                      'Mesagne': [{'Torre Santa Susanna': 12}, {'Brindisi': 13}, {'Latiano': 7}, {'San Donaci': 16},
                                  {'San Pancrazio Salentino': 16}, {'Oria': 16}],
                      'Oria': [{'Francavilla': 6}, {'Torre Santa Susanna': 9}, {'Latiano': 9}, {'Erchie': 10},
                               {'Mesagne': 15}],
                      'San Donaci': [{'Cellino San Marco': 4}, {'San Pancrazio Salentino': 6}, {'Mesagne': 9},
                                     {'Brindisi': 20}],
                      'San Michele Salentino': [{'San Vito dei Normanni': 7}, {'Ceglie Messapica': 9}, {'Latiano': 11},
                                                {'Ostuni': 12}, {'Francavilla Fontana': 12}],
                      'San Pancrazio Salentino': [{'Erchie': 9}, {'San Donaci': 9}, {'Torre Santa Susanna': 10},
                                                  {'Mesagne': 16}],
                      'San Pietro Vernotico': [{'Cellino San Marco': 4}, {'Torchiarolo': 5}, {'Brindisi': 16}],
                      'San Vito dei Normanni': [{'SAn Michele Salentino': 7}, {'Carovigno': 7}, {'Latiano': 12},
                                                {'Ostuni': 14}, {'Brindisi': 20}],
                      'Torchiarolo': [{'San Pietro Vernotico': 4}],
                      'Torre Santa Susanna': [{'Erchie': 3}, {'Oria': 9}, {'San Pancrazio': 9}, {'Mesagne': 12}],
                      'Villa Castelli': [{'Ceglie Messapica': 8}, {'Francavilla Fontana': 11}]

            }

            ospedaliFG={
                'Cerignola',
                'Foggia',
                'Manfredonia',
                'San Giovanni Rotondo',
                'San Severo'
            }

            ospedaliBT={
                'Barletta',
                'Andria',
                'Bisceglie',
                'Trani'
            }

            ospedaliBA={
                'Acquaviva Delle Fonti',
                'Altamura',
                'Bari',
                'Putignano',
                'Monopoli',
                'Triggiano'
            }

            ospedaliBR={
                'Brindisi',
                'Francavilla Fontana',
                'Ostuni',
            }

            ospedaliTA={
                'Taranto',
                'Manduria',
                'Castellaneta',
                'Grottaglie',
                'Martina Franca'
            }

            ospedaliLE={
                'Lecce',
                'Gallipoli',
                'Casarano',
                'Copertino',
                'Galatina',
                'Scorrano',
                'Tricase'
            }











